# Nginx Docker SSL
version: "3"

services:
  nginx:
    build: .
    ports:
      - "443:8443"
    volumes: &nginx-volumes
      - ./dist/apps/shell:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

volumes:
  nginx-volumes:
  sockdata:
  ssldata:
