## Mark Shust's Docker Configuration for Magento
## (https://github.com/markshust/docker-magento)
##
## Version 42.0.0

## To use SSH, see https://github.com/markshust/docker-magento#ssh
## Linux users, see https://github.com/markshust/docker-magento#linux

## If you changed the default Docker network, you may need to replace
## 172.17.0.1 in this file with the result of:
## docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}'

version: "3"

services:
  nginx:
    build: .
    ports:
      - "443:8443"
    volumes: &nginx-volumes
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

volumes:
  nginx-volumes:
  sockdata:
  ssldata: